local M = {
    "nvim-treesitter/nvim-treesitter",
    build = function()
        require("nvim-treesitter.install").update({ with_sync = true })()
    end,
    config = function () 
        local configs = require("nvim-treesitter.configs")
        configs.setup({
            ensure_installed = {
                "arduino",
                "asm",
                "awk",
                "bash",
                "bibtex",
                "c",
                "c_sharp",
                "cmake",
                "comment",
                "cpp",
                "css",
                "csv",
                "diff",
                "dockerfile",
                "elixir",
                "erlang",
                "fish",
                "git_config",
                "git_rebase",
                "gitattributes",
                "gitcommit",
                "gitignore",
                "go",
                "html",
                "http",
                "java",
                "javascript",
                "jq",
                "jsdoc",
                "json",
                "kdl",
                "kotlin",
                "latex",
                "llvm",
                "lua",
                "luadoc",
                "make",
                "markdown",
                "markdown_inline",
                "nasm",
                "nginx",
                "nix",
                "objdump",
                "passwd",
                "pem",
                "perl",
                "php",
                "phpdoc",
                "po",
                "powershell",
                "puppet",
                "python",
                "query",
                "regex",
                "ruby",
                "rust",
                "scss",
                "sql",
                "ssh_config",
                "strace",
                "svelte",
                "swift",
                "terraform",
                "tmux",
                "toml",
                "tsx",
                "typescript",
                "typst",
                "udev",
                "vala",
                "vim",
                "vimdoc",
                "yaml",
                "zig",
            },
            sync_install = false,
            highlight = { enable = true },
            indent = { enable = true },
        })
    end,
}

return { M }
