return {
    'nvim-treesitter/nvim-treesitter',
    lazy = false,
    build = ':TSUpdate',

    config = function()
        require('nvim-treesitter').setup {}

        require('nvim-treesitter').install {
            'asm',
            'bash',
            'c',
            'c_sharp',
            'cmake',
            'cpp',
            'css',
            'csv',
            'desktop',
            'diff',
            'dockerfile',
            'git_config',
            'git_rebase',
            'gitattributes',
            'gitcommit',
            'gitignore',
            'go',
            'graphql',
            'hcl',
            'html',
            'ini',
            'java',
            'javascript',
            'jq',
            'json',
            'kdl',
            'kitty',
            'kotlin',
            'latex',
            'lua',
            'make',
            'markdown',
            'nasm',
            'nix',
            'nu',
            'php',
            'ruby',
            'rust',
            'scss',
            'sql',
            'ssh_config',
            'svelte',
            'toml',
            'typescript',
            'typst',
            'udev',
            'vala',
            'vim',
            'xml',
            'yaml',
            'zig',
            'zsh',
        }
    end,
}
